### ISSUE TITLE
RecursionError

### ISSUE THREAD

**Issue by alexmarco** [FelixTheC/strongtyping#105]
**Describe the bug**
When try to check this code:
```python
from strongtyping.strong_typing import match_class_typing
import dataclasses as dc
import typing as t

@match_class_typing
@dc.dataclass
class QueryPipelineFunctions:
    """"""
    callables: t.List[str]

QueryPipelineFunctions(["a", "b"])

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\.virtualenvs\arqdat\lib\site-packages\strongtyping\strong_typing.py", line 54, in inner
    cached_key = (func, args.__str__(), kwargs.__str__())
  File "C:\Users\arqdat\lib\site-packages\strongtyping\strong_typing.py", line 54, in inner
    cached_key = (func, args.__str__(), kwargs.__str__())
  File "C:\Users\arqdat\lib\site-packages\strongtyping\strong_typing.py", line 54, in inner
    cached_key = (func, args.__str__(), kwargs.__str__())
  [Previous line repeated 329 more times]
  File "C:\Users\arqdat\lib\site-packages\strongtyping\strong_typing.py", line 49, in inner
    if arg_names and severity_level > SEVERITY_LEVEL.DISABLED.value:
RecursionError: maximum recursion depth exceeded while calling a Python object
```

**Python Version used**
Python 3.8.8

**Package Version used**
strongtyping 2.2.2

**Addon in use**
strongtyping_modules [no]

**To Reproduce**

**Expected behavior**
Expect that no error is found

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [Windows 11]

**Smartphone (please complete the following information):**

**Additional context**

**Comment by FelixTheC** [comment]
new release 2.2.3 should fix this error
